included:
  - Sources
  - Tests
excluded:
  - .build
  - DerivedData

disabled_rules:
  - closure_body_length
  - closure_spacing
  - file_name
  - function_parameter_count
  - identifier_name
  - large_tuple
  - missing_docs
  - nesting
  - nslocalizedstring_require_bundle
  - trailing_comma
  - type_name
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_whitespace

cyclomatic_complexity:
  warning: 12
  error: 20

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

line_length:
  warning: 200
  error: 250

type_body_length:
  warning: 400
  error: 600
