included:
  - Sources
  - Tests
excluded:
  - .build
  - DerivedData

disabled_rules:
  - closure_body_length
  - closure_spacing
  - cyclomatic_complexity
  - file_length
  - file_name
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - missing_docs
  - nesting
  - nslocalizedstring_require_bundle
  - todo
  - trailing_comma
  - type_body_length
  - type_name
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_whitespace
